# Generated by Django 2.0.4 on 2018-04-17 19:13

from django.db import migrations, models
import django.db.models.deletion
import photoblog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_es', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('slug_es', models.SlugField(blank=True, max_length=100, null=True)),
                ('slug_en', models.SlugField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('description_es', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_es', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('slug_es', models.SlugField(blank=True, default='', null=True)),
                ('slug_en', models.SlugField(blank=True, default='', null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('description_es', models.CharField(blank=True, max_length=500, null=True)),
                ('description_en', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photoblog_collection_set', related_query_name='photoblog_collection', to='photoblog.Category')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'ordering': ('-created_at',),
                'permissions': (('publish_collection', 'can publish collection'), ('unpublish_collection', 'can un-publish collection'), ('view_unpublished', 'can view collection drafts')),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('mm', 'Milimeters'), ('cm', 'Centimeters'), ('m', 'Meters'), ('in', 'Inches'), ('ft', 'Feet')], default='in', max_length=2)),
                ('height', models.FloatField(null=True, verbose_name='height')),
                ('length', models.FloatField(null=True, verbose_name='length')),
                ('width', models.FloatField(blank=True, help_text='If your art piece were 3 dimensional, how wide (thick) would it be', null=True, verbose_name='width')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_es', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('slug_es', models.SlugField(blank=True, default='', null=True)),
                ('slug_en', models.SlugField(blank=True, default='', null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('description_es', models.CharField(blank=True, max_length=500, null=True)),
                ('description_en', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photoblog_entry_set', related_query_name='photoblog_entry', to='photoblog.Category')),
                ('collections', models.ManyToManyField(blank=True, related_name='entries', to='photoblog.Collection')),
            ],
            options={
                'verbose_name': 'entry',
                'verbose_name_plural': 'entries',
                'ordering': ('-created_at',),
                'permissions': (('publish_entry', 'can publish entry'), ('unpublish_entry', 'can un-publish entry'), ('view_unpublished', 'can view entry drafts')),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_es', models.CharField(max_length=100, null=True, unique=True)),
                ('title_en', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('caption_es', models.CharField(blank=True, max_length=255, null=True)),
                ('caption_en', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to=photoblog.models.image_directory_path)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='accounts.User')),
                ('entries', models.ManyToManyField(blank=True, related_name='images', to='photoblog.Entry')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_es', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('slug_es', models.SlugField(blank=True, default='', null=True)),
                ('slug_en', models.SlugField(blank=True, default='', null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('description_es', models.CharField(blank=True, max_length=500, null=True)),
                ('description_en', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
                ('text_es', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photoblog_story_set', related_query_name='photoblog_story', to='photoblog.Category')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_of_photoblog_story', related_query_name='photoblog_story', to='photoblog.Image')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photoblog_story_set', related_query_name='photoblog_story', to='accounts.User')),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
                'ordering': ('-created_at',),
                'permissions': (('publish_story', 'can publish story'), ('unpublish_story', 'can un-publish story'), ('view_unpublished', 'can view story drafts')),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='image',
            name='stories',
            field=models.ManyToManyField(blank=True, related_name='images', to='photoblog.Story'),
        ),
        migrations.AddField(
            model_name='entry',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_of_photoblog_entry', related_query_name='photoblog_entry', to='photoblog.Image'),
        ),
        migrations.AddField(
            model_name='entry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photoblog_entry_set', related_query_name='photoblog_entry', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='entry',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='photoblog.Dimension'),
        ),
        migrations.AddField(
            model_name='collection',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_of_photoblog_collection', related_query_name='photoblog_collection', to='photoblog.Image'),
        ),
        migrations.AddField(
            model_name='collection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photoblog_collection_set', related_query_name='photoblog_collection', to='accounts.User'),
        ),
        migrations.AlterUniqueTogether(
            name='story',
            unique_together={('slug', 'created_by'), ('title', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('slug', 'created_by'), ('title', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('slug', 'created_by'), ('title', 'created_by')},
        ),
    ]
